- name: Block IP Address for Suspicious Activity
  hosts: "{{ target_host }}"
  gather_facts: false
  become: yes
  tasks:
    - name: Block the source IP using iptables
      ansible.builtin.iptables:
        chain: OUTPUT
        source: "{{ target_host }}"
        destination: "{{ target }}"
        jump: DROP
        comment: "Blocked due to suspicious activity"
      register: iptables_result

    - name: Save iptables rules
      ansible.builtin.shell:
        cmd: "iptables-save > /etc/iptables/rules.v4"
      when: iptables_result.changed